#mock mac file for Isolde VANDLE Setup

################
# OUTPUT SETUP #
################

# Set the output filename prefix
/nDet/output/filename singlebar_barTOF_test.root
/nDet/output/title 1 bar 1.0 MeV esr wrapping pseudo iso

/nDet/output/debug true

# Setup information about the PMT response
/nDet/output/trace/setRisetime 2
/nDet/output/trace/setFalltime 20
/nDet/output/trace/setTimeSpread 0.35
/nDet/output/trace/setGain 0.5E3
/nDet/output/trace/setBaseline 7.5
/nDet/output/trace/setJitter 0.15

# Setup the PMT light pulse output
/nDet/output/trace/setTraceDelay 60
/nDet/output/trace/setTraceLength 500
/nDet/output/trace/setBitRange 16

/nDet/output/trace/setCfdFraction 0.5
/nDet/output/trace/setIntegralLow 5
/nDet/output/trace/setIntegralHigh 10

##############
#eventually this will be an added functionality to call for adding experimental setups
##############
#/nDet/World/buildIDS


###############
# ARRAY Setup #
###############


########## Must Have's ###############
#/nDet/detector/setMylarThickness 0.025
#/nDet/detector/setGreaseThickness 1
#/nDet/detector/setWrapping esr
#/nDet/detector/setWindowThickness 1.0
######################################

########## Must Have's ###############
/nDet/detector/setMylarThickness 0.025
/nDet/detector/setGreaseThickness 1
/nDet/detector/setWrapping mylar
/nDet/detector/setWindowThickness 1.0
######################################

# Medium VANDLE (5x3x120 cm^3)
/nDet/detector/setDetectorLength 120.0
/nDet/detector/setDetectorWidth 3.0
/nDet/detector/setDetectorThickness 50.0
/nDet/detector/setPmtDimensions 30.0
/nDet/detector/setPmtColumns 1
/nDet/detector/setPmtRows 1


/nDet/detector/addArray rectangle 105 45 135 26

#/nDet/detector/setPosition 0 0 100 cm
#/nDet/detector/setRotation 90 0 0
#/nDet/detector/addGeometry rectangle 

/nDet/detector/update

################
# SOURCE SETUP #
################

# Available source types: 137Cs 60Co 133Ba 241Am 90Sr 252Cf 49K
#/nDet/source/type 49K

#/nDet/source/type gamma 0.02
/nDet/source/type neutron 
/nDet/source/shape point
#/nDet/source/setGaussianEnergy 1 0.5
/nDet/source/setUniformEnergy 0.1 3 

# Set isotropic source (0=off, 1=psuedo, 2=realistic)
#/nDet/source/direction 90 270 0
/nDet/source/iso 2


/run/beamOn 3000000
