/** @file version.hh
  * @brief Header containing the current NEXTsim commit number which is being used
  * This file is automatically generated by CMake whenever a change to the current
  * repository branch is detected and should not be modified by the user
  */

#ifndef NDET_VERSION_HH
#define NDET_VERSION_HH

#define VERSION_STRING "8ed0589-8HeGeometry (2024-10-11)"

#endif
