/** @file version.hh
  * @brief Header containing the current NEXTsim commit number which is being used
  * This file is automatically generated by CMake whenever a change to the current
  * repository branch is detected and should not be modified by the user
  */

#ifndef NDET_VERSION_HH
#define NDET_VERSION_HH

#define VERSION_STRING "a0f642f-isolde (2021-12-01)"

#endif
